------------------- TEST DATA ENGINIER ------------------- 

-- 01

CREATE TABLE PRODUCTO (
			ID_PRODUCTO INT IDENTITY(1,1),
			NOMBRE_PRODUCTO VARCHAR(25),
			PRECIO_UNITARIO FLOAT);

CREATE TABLE VENTA (
			ID_VENTA INT IDENTITY(1,1),
			ID_PRODUCTO INT,
			FECHA_VENTA DATE,
			CANTIDAD_VENDIDA INT);


INSERT INTO PRODUCTO (NOMBRE_PRODUCTO,PRECIO_UNITARIO) VALUES
 ('Producto A', 10.99),
 ('Producto B', 5.99),
 ('Producto C', 7.99),
 ('Producto D', 12.99);

 SELECT * FROM PRODUCTO;

INSERT INTO VENTA(ID_PRODUCTO ,
			FECHA_VENTA ,
			CANTIDAD_VENDIDA ) VALUES 
 (1, '2022-01-01', 10),
 (1, '2022-01-15', 20),
 (2, '2022-02-01', 5),
 (3, '2022-03-01', 15),
 (4, '2022-04-01', 8),
 (1, '2022-05-01', 12),
 (2, '2022-06-01', 10),
 (3, '2022-07-01', 20),
 (4, '2022-08-01', 15);

 -- 03
 SELECT A.NOMBRE_PRODUCTO,
		SUM(A.PRECIO_UNITARIO*V.CANTIDAD_VENDIDA) FROM PRODUCTO A 
		INNER JOIN VENTA V ON A.ID_PRODUCTO = V.ID_PRODUCTO
		GROUP BY A.NOMBRE_PRODUCTO;
--04

SELECT  
	    MIN(PRECIO_UNITARIO), 
	   MAX(PRECIO_UNITARIO) 
		FROM PRODUCTO;

--5

SELECT MONTH(V.FECHA_VENTA) MES, AVG(A.PRECIO_UNITARIO*V.CANTIDAD_VENDIDA) VENTA
		FROM VENTA V INNER JOIN PRODUCTO A ON A.ID_PRODUCTO=V.ID_PRODUCTO
		GROUP BY MONTH(V.FECHA_VENTA);

--6

 SELECT A.NOMBRE_PRODUCTO,
		SUM(A.PRECIO_UNITARIO*V.CANTIDAD_VENDIDA) FROM PRODUCTO A 
		INNER JOIN VENTA V ON A.ID_PRODUCTO = V.ID_PRODUCTO
		GROUP BY A.NOMBRE_PRODUCTO
		HAVING SUM(A.PRECIO_UNITARIO*V.CANTIDAD_VENDIDA) > 100;

--7

SELECT FECHA_VENTA,
	LAG(PRECIO_UNITARIO*CANTIDAD_VENDIDA) OVER(ORDER BY FECHA_VENTA) VENTA_ANT,
	LEAD(PRECIO_UNITARIO*CANTIDAD_VENDIDA) OVER(ORDER BY FECHA_VENTA) VENTA_POS
	FROM VENTA V INNER JOIN PRODUCTO P ON P.ID_PRODUCTO=V.ID_PRODUCTO
	ORDER BY FECHA_VENTA;

--8

WITH TBA AS (SELECT NOMBRE_PRODUCTO,
			SUM(PRECIO_UNITARIO*CANTIDAD_VENDIDA) TOTAL
				  FROM VENTA V INNER JOIN PRODUCTO P ON P.ID_PRODUCTO=V.ID_PRODUCTO
				  GROUP BY NOMBRE_PRODUCTO)
SELECT NOMBRE_PRODUCTO,
	   RANK() OVER(ORDER BY TOTAL DESC) RANKING
	   FROM TBA;

--9


 SELECT A.NOMBRE_PRODUCTO,
		MONTH(V.FECHA_VENTA) MES,
		SUM(A.PRECIO_UNITARIO*V.CANTIDAD_VENDIDA) VENTA_TOTAL FROM PRODUCTO A 
		INNER JOIN VENTA V ON A.ID_PRODUCTO = V.ID_PRODUCTO
		GROUP BY A.NOMBRE_PRODUCTO,MONTH(V.FECHA_VENTA)
		HAVING SUM(A.PRECIO_UNITARIO*V.CANTIDAD_VENDIDA) > 100
		ORDER BY NOMBRE_PRODUCTO;

--10
WITH TBA AS (
SELECT MONTH(V.FECHA_VENTA) MES, NOMBRE_PRODUCTO, MAX(A.PRECIO_UNITARIO*V.CANTIDAD_VENDIDA) VENTA FROM PRODUCTO A 
		INNER JOIN VENTA V ON A.ID_PRODUCTO = V.ID_PRODUCTO
		WHERE MONTH(V.FECHA_VENTA) = 3
		GROUP BY MONTH(V.FECHA_VENTA),NOMBRE_PRODUCTO)
SELECT NOMBRE_PRODUCTO FROM TBA WHERE VENTA = (SELECT MAX(VENTA) FROM TBA);

--11

WITH TBA AS (
SELECT  NOMBRE_PRODUCTO, MAX(A.PRECIO_UNITARIO*V.CANTIDAD_VENDIDA) VENTA FROM PRODUCTO A 
		INNER JOIN VENTA V ON A.ID_PRODUCTO = V.ID_PRODUCTO
		WHERE FECHA_VENTA BETWEEN '2022-01-01' AND '2022-03-31'
		GROUP BY NOMBRE_PRODUCTO) 
SELECT NOMBRE_PRODUCTO FROM TBA
	WHERE VENTA = (SELECT MAX(VENTA) FROM TBA);

-- 12

 SELECT DISTINCT MONTH(V.FECHA_VENTA) MES,
		SUM(A.PRECIO_UNITARIO*V.CANTIDAD_VENDIDA) OVER( PARTITION BY MONTH(V.FECHA_VENTA)) VENTA_TOTAL FROM PRODUCTO A 
		INNER JOIN VENTA V ON A.ID_PRODUCTO = V.ID_PRODUCTO;



--------- EXTRAS --------
ALTER TABLE PRODUCTO 
ADD DISPONIBLE VARCHAR(25);
--------------------------
UPDATE PRODUCTO
SET DISPONIBLE = CASE WHEN PRECIO_UNITARIO < 8 THEN 'SI'
					ELSE 'NO' END;
--------------------------
ALTER TABLE PRODUCTO 
ADD NEWIDA INT;
--------------------------
ALTER TABLE PRODUCTO 
DROP COLUMN NEWIDA;
--------------------------
ALTER TABLE PRODUCTO 
ADD NEWIDA VARCHAR(5);
--------------------------
UPDATE PRODUCTO 
SET NEWIDA = CONCAT(RIGHT(ID_PRODUCTO,1),LEFT(DISPONIBLE,2));
--------------------------
SELECT * FROM PRODUCTO;
