


-------------------SQL -------------------------
---------- DDL ---------------LENGUAJE DE DEFINICION DE LOS DATOS (OBJETOS)
--CREATE , ALTER , DROP 

---------- DML ---------------LENGUAJE DE MANIPULACION DE LOS DATOS (MANIPULAR) 

--SELECT , INSERT , UPDATE , DELETE 
------------------------------------------------------------------------------

--1.- CREAR UNA TABLA IGUAL A LA TABLA ANTERIORMENTE CREADA 

--- CREATE 
CREATE TABLE TC_EMPLEADO_1
(COD_EMPLEADO INT NOT NULL , -- TIPO DE DATO ENTERO Y NOT NULL PARA QUE LA COLUMNA NO ACEPTE NULOS
NOMBRE VARCHAR(150) NULL,    -- TIPO DE DATO VARCHAR (TEXTO)
EDAD INT ,                   -- TIPO DE DATO ENTERO
FEC_NACIMIENTO DATE,         -- TIPO DE DATO DATE (FECHA)  
SUELDO DECIMAL(18,3)         -- TIPO DE DATO DECIMAL 
)

--- DROP --- ELIMINAR LA TABLA 

DROP TABLE TC_EMPLEADO

---- ALTER 
-- ALTERAR UNA TABLA 

---1.- AGREGAR UN NUEVO CAMPO A LA TABLA 

ALTER TABLE TC_EMPLEADO_1
ADD GENERO CHAR(10) 

--- 2.- ELIMINAR UNA COLUMNA DE LA TABLA 

ALTER TABLE TC_EMPLEADO_1
DROP COLUMN SUELDO

---3.- CAMBIAR EL TIPO DE DATO DE UNA COLUMNA 
ALTER TABLE TC_EMPLEADO_1
ALTER COLUMN GENERO INT 

----------------------------------------------

--- SELECT --- PERMITE SELECIONAR EL CONTENIDO DE UNA TABLA 


--- SINTAXIS 

SELECT --- LISTAR COLUMNAS DE TABLAS 
FROM   --- INDICAS LA TABLA A CONSULTAR 


-- SELECIONANDO DE LA TABLA ANIMALES 
--- SELECIONAR COLUMNAS EN ESPECIFICAS 

SELECT COD , NOMBRE 
FROM ANIMALES

-- SELECIONAR TODAS LAS COLUMNAS DE UNA TABLA 

SELECT *  -- ALL COLUMNS 
FROM ANIMALES

